AWSTemplateFormatVersion: "2010-09-09"
Description: "Single ECR repository for the Clothing Wishlist API (shared image)."

Parameters:
  RepositoryName:
    Type: String
    Default: "clothing-service"
    Description: "ECR repository name for the Clothing Wishlist API image."

Resources:
  ClothingEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: false
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: ECR repository URI for the Clothing API
    Value: !GetAtt ClothingEcrRepo.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-ClothingEcrRepoUri"
