AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Fargate + API Gateway REST API with API Key for clothing-app (wishlist de prendas de ropa)"

Parameters:
  ImageName:
    Type: String
    Description: ECR Image Name
    Default: clothing-app:latest

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least 2 Subnets

  DBDynamoName:
    Type: String
    Default: "clothing_items"
    Description: DynamoDB table name used by clothing-app

# ============================================================================
# NETWORKING RESOURCES
# ============================================================================
Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks (clothing-app)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 172.31.0.0/16 #Modificando para que el acceso sea solo mediante la vpcIp y así no dejarlo abierto 

  # ============================================================================
  # LOAD BALANCER RESOURCES
  # ============================================================================
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: clothing-nlb
      Type: network
      Scheme: internal
      Subnets: !Ref SubnetIds

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: clothing-tg
      Port: 8080
      Protocol: TCP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref NLB
      Port: 8080
      Protocol: TCP

  # ============================================================================
  # ECS RESOURCES
  # ============================================================================
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: clothing-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: clothing-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      ContainerDefinitions:
        - Name: clothing-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/clothing
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: clothing
              awslogs-create-group: "true"
          Environment:
            - Name: DB_DYNAMONAME
              Value: !Ref DBDynamoName

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - Listener
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: clothing-service
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: clothing-container
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

  # ============================================================================
  # API GATEWAY RESOURCES
  # ============================================================================
  VPCLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: clothing-vpc-link
      TargetArns:
        - !Ref NLB

  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: clothing-api
      Description: API para gestión de wishlist de prendas de ropa

  ClothingResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: clothing

  ClothingItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !Ref ClothingResource
      PathPart: "{id}"

  PostClothingMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "http://${NLB.DNSName}:8080/clothing"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink

  GetClothingMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NLB.DNSName}:8080/clothing"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink

  GetClothingItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingItemResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NLB.DNSName}:8080/clothing/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  PutClothingItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingItemResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: PUT
        Uri: !Sub "http://${NLB.DNSName}:8080/clothing/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  DeleteClothingItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingItemResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: DELETE
        Uri: !Sub "http://${NLB.DNSName}:8080/clothing/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  OptionsClothingMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  OptionsClothingItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ClothingItemResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Health endpoint added at API root: /health
  HealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: health

  HealthGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref HealthResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NLB.DNSName}:8080/health"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostClothingMethod
      - GetClothingMethod
      - GetClothingItemMethod
      - PutClothingItemMethod
      - DeleteClothingItemMethod
      - OptionsClothingMethod
      - OptionsClothingItemMethod
      - HealthGetMethod

    Properties:
      RestApiId: !Ref RestAPI

  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref APIDeployment
      StageName: prod

  APIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: clothing-api-key
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: APIStage
    Properties:
      UsagePlanName: clothing-usage-plan
      ApiStages:
        - ApiId: !Ref RestAPI
          Stage: !Ref APIStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref APIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

# ============================================================================
# API GATEWAY DOCUMENTATION PARTS (Clothing)
# ============================================================================
  ClothingApiDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: API
      Properties: |
        {
          "description": "API para gestión de prendas con autenticación por API Key. Permite operaciones CRUD sobre una base de datos DynamoDB.",
          "info": {
            "title": "Clothing API",
            "version": "1.0.0",
            "contact": { "name": "API Support" }
          }
        }

  ClothingCollectionResourceDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: RESOURCE
        Path: /clothing
      Properties: |
        { "description": "Recurso para gestionar la colección de prendas" }

  GetClothingMethodDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: METHOD
        Path: /clothing
        Method: GET
      Properties: |
        {
          "summary": "Obtener todas las prendas",
          "description": "Retorna una lista de todas las prendas almacenadas",
          "tags": ["Clothing"],
          "responses": {
            "200": { "description": "Lista de prendas obtenida exitosamente" },
            "401": { "description": "No autorizado - API Key inválida o faltante" },
            "500": { "description": "Error interno del servidor" }
          }
        }

  PostClothingMethodDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: METHOD
        Path: /clothing
        Method: POST
      Properties: |
        {
          "summary": "Crear una prenda",
          "description": "Crea una nueva prenda con los datos proporcionados",
          "tags": ["Clothing"],
          "requestBody": {
            "description": "Datos de la prenda a crear",
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": ["name", "brand", "size", "color", "price"],
                  "properties": {
                    "name": { "type": "string", "example": "Chaqueta" },
                    "brand": { "type": "string", "example": "Zara" },
                    "size": { "type": "string", "example": "M" },
                    "color": { "type": "string", "example": "Negro" },
                    "price": { "type": "number", "minimum": 0, "example": 79.99 },
                    "wishlist": { "type": "boolean", "example": false },
                    "notes": { "type": "string", "example": "Edición limitada" }
                  }
                }
              }
            }
          },
          "responses": {
            "201": { "description": "Prenda creada exitosamente" },
            "400": { "description": "Solicitud inválida - datos incorrectos" },
            "401": { "description": "No autorizado - API Key inválida" }
          }
        }

  ClothingItemResourceDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: RESOURCE
        Path: /clothing/{id}
      Properties: |
        { "description": "Recurso para gestionar una prenda específica por su ID" }

  GetClothingItemMethodDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: METHOD
        Path: /clothing/{id}
        Method: GET
      Properties: |
        {
          "summary": "Obtener una prenda por ID",
          "description": "Retorna los detalles de una prenda identificada por su ID",
          "tags": ["Clothing"],
          "parameters": [
            { "name": "id", "in": "path", "required": true, "schema": { "type": "string" }, "description": "ID único de la prenda" }
          ],
          "responses": {
            "200": { "description": "Prenda encontrada" },
            "404": { "description": "Prenda no encontrada" },
            "401": { "description": "No autorizado" }
          }
        }

  PutClothingItemMethodDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: METHOD
        Path: /clothing/{id}
        Method: PUT
      Properties: |
        {
          "summary": "Actualizar una prenda",
          "description": "Actualiza los datos de una prenda existente",
          "tags": ["Clothing"],
          "parameters": [
            { "name": "id", "in": "path", "required": true, "schema": { "type": "string" }, "description": "ID de la prenda a actualizar" }
          ],
          "responses": {
            "200": { "description": "Prenda actualizada exitosamente" },
            "404": { "description": "Prenda no encontrada" },
            "400": { "description": "Datos inválidos" }
          }
        }

  DeleteClothingItemMethodDocumentation:
    Type: AWS::ApiGateway::DocumentationPart
    Properties:
      RestApiId: !Ref RestAPI
      Location:
        Type: METHOD
        Path: /clothing/{id}
        Method: DELETE
      Properties: |
        {
          "summary": "Eliminar una prenda",
          "description": "Elimina una prenda de la base de datos",
          "tags": ["Clothing"],
          "parameters": [
            { "name": "id", "in": "path", "required": true, "schema": { "type": "string" }, "description": "ID de la prenda a eliminar" }
          ],
          "responses": {
            "200": { "description": "Prenda eliminada exitosamente" },
            "404": { "description": "Prenda no encontrada" }
          }
        }

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  APIEndpoint:
    Description: API Gateway URL
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"

  APIKeyId:
    Description: API Key ID
    Value: !Ref APIKey

  HealthCheckUrl:
    Description: Health Check Endpoint
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/health"

  ClothingEndpoint:
    Description: Clothing API Endpoint
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/clothing"
